stages: # List of stages for jobs, and their order of execution
  - build-app
  - build-docker-image
  - push-to-glcr
  - push-to-ecr

build-app:
  stage: build-app
  image: node:18.4.0-alpine3.16
  script:
    - cd app/
    - npm install
    - npm run build
  artifacts:
    paths:
      - app/build/

build-docker-image:
  stage: build-docker-image
  image: docker
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -f Dockerfile.build . -t $CI_REGISTRY_IMAGE
    - docker push -a $CI_REGISTRY_IMAGE
