Vagrant.configure("2") do |config|
  # Box Settings
  # Define base image of the machine
  config.vm.box = "ubuntu/focal64"

  # Provider Settings
  # Use virtualbox as a VM provider
  config.vm.provider "virtualbox" do |vb|

    # Virtual machine resources
    vb.memory = 4096
    vb.cpus = 4

    # Virtual machine name
    vb.name = "k8s-dev"
  end

  # Synced Folder Settings
  # Mount specified paths to host machine
  config.vm.synced_folder "./shared/scripts", "/opt/scripts"
  config.vm.synced_folder "./cluster", "/tmp/cluster"

  # Provision Settings
  # Execute given script on boot
  # config.vm.provision "shell", path: "./shared/scripts/bootstrap.sh"
end