name: Enhancement Job
description: Default issue form for new enhancement jobs.
assignees: huyagci
labels: [":recycle: Enhancement"]
body:
  - type: textarea
    attributes:
      label: "🗑️ Discarded"
      description: "Features written here are discarded."
      value: |
        1. Discarded Feature 1
        2. Discarded Feature 1
        3. Discarded Feature 1
    validations:
      required: true

  - type: textarea
    attributes:
      label: "✅ Improvements"
      description: "Features written here will be improved accordingly."
      value: |
        1. Improvement 1 
        2. Improvement 1 
        3. Improvement 1
    validations:
      required: true

  - type: textarea
    attributes:
      label: "📌 Remarks & Notes"
      description: "Submit any kind of remarks or notes here if any. (Remove list items or info text)"
      value: |
        "No additional information exists."

        - Information 1
        - Information 2
        - Information 3
    validations:
      required: false

  - type: textarea
    attributes:
      label: "🗃️ Resources"
      description: "Submit the link of used resources here if any. (Remove list items or info text)"
      value: |
        "No additional resources were used."

        - [#res-desc-here](#link-here)
        - [#res-desc-here](#link-here)
        - [#res-desc-here](#link-here)
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## :warning: Warnings
        - Select the sub-label by related scope.
        - Add this issue to the project board.
        - Select the milestone by corresponding sprint.
