#The latest Nginx release on the latest Alpine base image is selected due to its small size as a web server container.
# Nginx 1.22 (Stable Version) - Alpine 3.16 (Stable Version)
FROM nginx:stable-alpine

# Pre-defined annotation keys of OCI (Open Container Initiative) are used since these are more widely recognized metadata keys.
# https://github.com/opencontainers/image-spec/blob/main/annotations.md
LABEL org.opencontainers.image.created="2022-07-04"
LABEL org.opencontainers.image.authors="hasanumutyagci@gmail.com"
LABEL org.opencontainers.image.url=""
LABEL org.opencontainers.image.source=""
LABEL org.opencontainers.image.vendor="Hasan Umut Yagci"
LABEL org.opencontainers.image.title="Protein App"
LABEL org.opencontainers.image.description="Simple React application customized for Protein DevOps Bootcamp Final Project"

# The working directory of the container. (Nginx Web server default location)
WORKDIR /usr/share/nginx/html

# # # Copy the contents of build/ directory to the working directory.
# # Uncomment and use this on your local image builds.
# COPY ./app/build/ .

# # To be used in Gitlab CI/CD. (Parent directories are removed in artifact archive)
# Check gitlab-ci.yml > Compile Job > after_script & artifacts > paths
COPY ./build .

# Expose container port 80 for HTTP access. (Default web port)
EXPOSE 80