# The latest Node.js release on top of the latest Alpine (due to its small size) is selected as a base image for the development environment.
# Node.js 18.6.0 (Current Version) - Alpine 3.16 (Stable Version)
FROM node:18.6.0-alpine3.16

# Pre-defined annotation keys of OCI (Open Container Initiative) are used since these are more widely recognized metadata keys.
# https://github.com/opencontainers/image-spec/blob/main/annotations.md
LABEL org.opencontainers.image.created="2022-07-04"
LABEL org.opencontainers.image.authors="hasanumutyagci@gmail.com"
LABEL org.opencontainers.image.vendor="Hasan Umut Yagci"
LABEL org.opencontainers.image.title="Protein App"
LABEL org.opencontainers.image.description="React development environment container for Protein DevOps Bootcamp Final Project"

# The working directory of the container is protein-app under the /tmp directory.
WORKDIR /tmp/protein-app

# Copy the contents of the app/ directory to working directory.
COPY ./docker/app .

# Run "npm clean-install" command including devDependecies.
RUN npm ci --include=dev

# Expose default react development server port of the container.
EXPOSE 3000

# Default command of the container.
ENTRYPOINT [ "npm" ]

# Start react development server.
CMD [ "start" ]