stages:
  - Plan
  - Apply
  - Destroy

variables:
  TF_ROOT: $CI_PROJECT_DIR/terraform

.config:
  image:
    name: hashicorp/terraform:light #same as latest
    entrypoint: [""]
    pull_policy: if-not-present
  before_script:
    - cd $TF_ROOT
    - terraform fmt
    - terraform init -input=false #--backend-config="access_key=$AWS_ACCESS_KEY" -backend-config="secret_key=$AWS_SECRET_KEY"

terraform plan:
  extends: .config
  stage: Plan
  script:
    - terraform plan -out aws.tfplan -input=false
  artifacts:
    when: on_success
    name: terraform-plan
    paths:
      - $TF_ROOT/aws.tfplan
    expire_in: 1 hrs

terraform apply:
  extends: .config
  when: manual
  stage: Apply
  dependencies:
    - terraform plan
  script:
    - terraform apply aws.tfplan -input=false -auto-approve

terraform destroy:
  extends: .config
  stage: Destroy
  when: manual
  needs: ["terraform plan", "terraform apply"]
  script:
    - terraform destroy -input=false -auto-approve
