---
apiVersion: v1
kind: Service
metadata:
  name: protein-app-svc
  namespace: production
  labels:
    app: protein-app
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32767
  selector:
    app: protein-app
