name: Push to Gitlab

on:
  push:
    branches:
      - dev

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  push:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git Settings
        run: |
          git config --global user.name "Hasan Umut Yagci"
          git config --global user.email "hasanumutyagci@gmail.com"

      - name: Add Gitlab Repository to Git Remotes
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
          GITLAB_URL: ${{ secrets.GITLAB_REPO_URL }}
        run: |
          git remote set-url gitlab "https://oauth2:${GITLAB_TOKEN}@${GITLAB_URL}"

      - name: Push to Gitlab
        run: git push --force gitlab dev
