name: Push to Gitlab

on:
  push:
    branches:
      - dev

  pull_request:
    branches:
      - main

  workflow_dispatch:
    push:
    branches:
      - dev

jobs:
  push:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git Settings
        run: |
          git config --global user.name "Hasan Umut Yagci"
          git config --global user.email "hasanumutyagci@gmail.com"

      - name: Add Gitlab Repository to Git Remotes
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
        run: git remote add gitlab "https://oauth2:${GITLAB_TOKEN}@gitlab.com/huyagci/bootcamp-final-project.git"

      - name: Push to Gitlab
        run: git push gitlab dev --force
