name: Push to Docker Hub

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        run: |
          docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_TOKEN}

      - name: Docker Build
        run: docker build . -f Dockerfile.dev -t huyagci/react-app:latest

      - name: Docker Push
        run: docker push huyagci/react-app
