name: Push to Docker Hub

on:
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
  DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO_NAME }}

jobs:
  dockerize-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        run: |
          echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - name: Docker Build
        run: docker build . -f docker/Dockerfile.dev -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:development

      - name: Docker Push
        run: docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:development
